fs=100000;
Ac=1;
Am=1;
fm=200;
fc=5000;
B=20;
t=(0:.01*fs)/fs;
wc=2*pi*fc;
wm=2*pi*fm;
m_t=Am*cos(wm*t);
subplot(3,1,1);
plot(t,m_t);
title('Modulating or Message signal(fm=35Hz)');
c_t=Ac*cos(wc*t);
subplot(3,1,2);
plot(t,c_t);
title('Carrier signal(fm=500Hz)');
s_t=Ac*cos((wc*t)+B*sin(wm*t));
subplot(3,1,3);
plot(t,s_t,'m');
title('Modulated signal');
